// SPDX-License-Identifier: GPL-2.0-only
/*
 * Qualcomm sa535m (echo) pinctrl
 *
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 *
 */

#include <dm.h>

#include "pinctrl-qcom.h"

#define MAX_PIN_NAME_LEN 32
#define MSM_PIN_FUNCTION_COUNT 12

static char pin_name[MAX_PIN_NAME_LEN] __section(".data");

typedef unsigned int msm_pin_function[MSM_PIN_FUNCTION_COUNT];

#define PINGROUP(id, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11)\
	{\
		msm_mux_gpio, /* gpio mode */\
		msm_mux_##f1,\
		msm_mux_##f2,\
		msm_mux_##f3,\
		msm_mux_##f4,\
		msm_mux_##f5,\
		msm_mux_##f6,\
		msm_mux_##f7,\
		msm_mux_##f8,\
		msm_mux_##f9,\
		msm_mux_##f10,\
		msm_mux_##f11 /* egpio mode */\
	}

#define SDC_QDSD_PINGROUP(pg_name, ctl, pull, drv)\
	{\
		.name = pg_name,\
		.ctl_reg = ctl,\
		.io_reg = 0,\
		.pull_bit = pull,\
		.drv_bit = drv,\
		.oe_bit = -1,\
		.in_bit = -1,\
		.out_bit = -1,\
	}

enum echo_functions {
	msm_mux_gpio,
	msm_mux_adsp_ext,
	msm_mux_aoss_cti,
	msm_mux_atest_char0,
	msm_mux_atest_char1,
	msm_mux_atest_char2,
	msm_mux_atest_char3,
	msm_mux_atest_char_start,
	msm_mux_atest_usb0,
	msm_mux_atest_usb1,
	msm_mux_atest_usb2,
	msm_mux_atest_usb3,
	msm_mux_audio_ref_clk,
	msm_mux_bimc_dte0,
	msm_mux_bimc_dte1,
	msm_mux_char_exec_pending,
	msm_mux_char_exec_release,
	msm_mux_coex_uart,
	msm_mux_dbg_out_clk,
	msm_mux_ddr_bist_complete,
	msm_mux_ddr_bist_fail,
	msm_mux_ddr_bist_start,
	msm_mux_ddr_bist_stop,
	msm_mux_ddr_pxi0,
	msm_mux_ddr_pxi1,
	msm_mux_ebi2_a,
	msm_mux_ebi2_lcd,
	msm_mux_ebi2_lcd_te,
	msm_mux_emac0_cdc0,
	msm_mux_emac0_cdc1,
	msm_mux_emac0_mcg,
	msm_mux_emac0_ptp,
	msm_mux_emac1_cdc0,
	msm_mux_emac1_cdc1,
	msm_mux_emac1_mcg,
	msm_mux_emac1_ptp0,
	msm_mux_emac1_ptp1,
	msm_mux_emac1_ptp2,
	msm_mux_emac1_ptp3,
	msm_mux_emac2_cdc0,
	msm_mux_emac2_cdc1,
	msm_mux_emac2_mcg,
	msm_mux_emac2_ptp0,
	msm_mux_emac2_ptp1,
	msm_mux_emac2_ptp2,
	msm_mux_emac2_ptp3,
	msm_mux_emac_pps_in,
	msm_mux_espmi_coex_clk,
	msm_mux_espmi_coex_data,
	msm_mux_eth0_mdc,
	msm_mux_eth0_mdio,
	msm_mux_eth1_mdc,
	msm_mux_eth1_mdio,
	msm_mux_eth2_mdc,
	msm_mux_eth2_mdio,
	msm_mux_gcc_125_clk,
	msm_mux_gcc_gp1_clk,
	msm_mux_gcc_gp2_clk,
	msm_mux_gcc_gp3_clk,
	msm_mux_gcc_plltest_bypassnl,
	msm_mux_gcc_plltest_resetn,
	msm_mux_host_rst,
	msm_mux_i2c0_s,
	msm_mux_i2s0_data0,
	msm_mux_i2s0_data1,
	msm_mux_i2s0_sck,
	msm_mux_i2s0_ws,
	msm_mux_i2s1_data0,
	msm_mux_i2s1_data1,
	msm_mux_i2s1_sck,
	msm_mux_i2s1_ws,
	msm_mux_i2s2_data0,
	msm_mux_i2s2_data1,
	msm_mux_i2s2_sck,
	msm_mux_i2s2_ws,
	msm_mux_i2s_mclk,
	msm_mux_i3c0_s_scl,
	msm_mux_i3c0_s_sda,
	msm_mux_ibi_i3c,
	msm_mux_jitter_bist,
	msm_mux_modem_pps,
	msm_mux_native_tsense,
	msm_mux_nav_dr_sync,
	msm_mux_nav_gpio0,
	msm_mux_nav_gpio1_mira,
	msm_mux_nav_gpio1_mirb,
	msm_mux_nav_gpio2_mira,
	msm_mux_nav_gpio2_mirb,
	msm_mux_nav_gpio2_mirc,
	msm_mux_nav_gpio3,
	msm_mux_nav_gpio4,
	msm_mux_nav_gpio5,
	msm_mux_nav_rffe,
	msm_mux_pa_indicator,
	msm_mux_pci_e,
	msm_mux_pcie0_clkreq_n,
	msm_mux_pcie0_perstn,
	msm_mux_pcie1_clkreq_n,
	msm_mux_pcie2_clkreq_n,
	msm_mux_pcie3_clkreq_n,
	msm_mux_pcie3_perstn,
	msm_mux_pll_bist_sync,
	msm_mux_pll_clk_aux,
	msm_mux_pll_ref_clk,
	msm_mux_prng_rosc0,
	msm_mux_prng_rosc1,
	msm_mux_prng_rosc2,
	msm_mux_prng_rosc3,
	msm_mux_qdss_cti,
	msm_mux_qlink0_enable,
	msm_mux_qlink0_request,
	msm_mux_qlink0_wmss,
	msm_mux_qup0_se0_l0,
	msm_mux_qup0_se0_l1,
	msm_mux_qup0_se0_l2,
	msm_mux_qup0_se0_l3,
	msm_mux_qup0_se1_l2,
	msm_mux_qup0_se1_l3,
	msm_mux_qup0_se2_l0,
	msm_mux_qup0_se2_l1,
	msm_mux_qup0_se2_l2,
	msm_mux_qup0_se2_l3,
	msm_mux_qup0_se3_l0,
	msm_mux_qup0_se3_l1,
	msm_mux_qup0_se3_l2,
	msm_mux_qup0_se3_l3,
	msm_mux_qup0_se4_l2_mira,
	msm_mux_qup0_se4_l2_mirb,
	msm_mux_qup0_se4_l3_mira,
	msm_mux_qup0_se4_l3_mirb,
	msm_mux_qup0_se5_l0,
	msm_mux_qup0_se5_l1,
	msm_mux_qup0_se6_l0_mira,
	msm_mux_qup0_se6_l0_mirb,
	msm_mux_qup0_se6_l1_mira,
	msm_mux_qup0_se6_l1_mirb,
	msm_mux_qup0_se6_l2_mira,
	msm_mux_qup0_se6_l2_mirb,
	msm_mux_qup0_se6_l3_mira,
	msm_mux_qup0_se6_l3_mirb,
	msm_mux_qup0_se7_l0,
	msm_mux_qup0_se7_l1,
	msm_mux_qup0_se7_l2,
	msm_mux_qup0_se7_l3,
	msm_mux_qup0_se8_l2_mira,
	msm_mux_qup0_se8_l2_mirb,
	msm_mux_qup0_se8_l3_mira,
	msm_mux_qup0_se8_l3_mirb,
	msm_mux_qup0_se9_l0_mira,
	msm_mux_qup0_se9_l0_mirb,
	msm_mux_qup0_se9_l1_mira,
	msm_mux_qup0_se9_l1_mirb,
	msm_mux_qup0_se9_l2_mira,
	msm_mux_qup0_se9_l2_mirb,
	msm_mux_qup0_se9_l3_mira,
	msm_mux_qup0_se9_l3_mirb,
	msm_mux_rgmii0_rx_ctl,
	msm_mux_rgmii0_rxc,
	msm_mux_rgmii0_rxd0,
	msm_mux_rgmii0_rxd1,
	msm_mux_rgmii0_rxd2,
	msm_mux_rgmii0_rxd3,
	msm_mux_rgmii0_tx_ctl,
	msm_mux_rgmii0_txc,
	msm_mux_rgmii0_txd0,
	msm_mux_rgmii0_txd1,
	msm_mux_rgmii0_txd2,
	msm_mux_rgmii0_txd3,
	msm_mux_sdc1_tb_trig,
	msm_mux_sdc1_write_protect,
	msm_mux_sgmii_phy_intr0_n,
	msm_mux_sgmii_phy_intr1_n,
	msm_mux_sgmii_phy_intr2_n,
	msm_mux_spmi_coex_clk,
	msm_mux_spmi_coex_data,
	msm_mux_spmi_vgi,
	msm_mux_tesic_gp_in0,
	msm_mux_tesic_gp_in1,
	msm_mux_tesic_gp_in2,
	msm_mux_tesic_gp_in3,
	msm_mux_tesic_gp_in4,
	msm_mux_tesic_gp_in5,
	msm_mux_tesic_gp_in6,
	msm_mux_tesic_gp_out0,
	msm_mux_tesic_gp_out1,
	msm_mux_tesic_gp_out10,
	msm_mux_tesic_gp_out2,
	msm_mux_tesic_gp_out3,
	msm_mux_tesic_gp_out4,
	msm_mux_tesic_gp_out5,
	msm_mux_tesic_gp_out6,
	msm_mux_tesic_gp_out7,
	msm_mux_tesic_gp_out8,
	msm_mux_tesic_gp_out9,
	msm_mux_tesic_jtag,
	msm_mux_tesic_jtag_tck,
	msm_mux_tesic_jtag_tdi,
	msm_mux_tesic_jtag_tdo,
	msm_mux_tesic_jtag_tms,
	msm_mux_tmess_prng0,
	msm_mux_tmess_prng1,
	msm_mux_tmess_prng2,
	msm_mux_tmess_prng3,
	msm_mux_uim0_clk,
	msm_mux_uim0_data,
	msm_mux_uim0_present,
	msm_mux_uim0_reset,
	msm_mux_uim1_clk_mira,
	msm_mux_uim1_clk_mirb,
	msm_mux_uim1_data_mira,
	msm_mux_uim1_data_mirb,
	msm_mux_uim1_present_mira,
	msm_mux_uim1_present_mirb,
	msm_mux_uim1_reset_mira,
	msm_mux_uim1_reset_mirb,
	msm_mux_usb0_hs,
	msm_mux_vfr_0,
	msm_mux_vfr_1,
	msm_mux_vsense_trigger_mirnat,
	msm_mux_wcn_sw,
	msm_mux_wcn_sw_ctrl,
	msm_mux__,
};

#define MSM_PIN_FUNCTION(fname)\
	[msm_mux_##fname] = {#fname, msm_mux_##fname}

static const struct pinctrl_function msm_pinctrl_functions[] = {
	MSM_PIN_FUNCTION(gpio),
	MSM_PIN_FUNCTION(adsp_ext),
	MSM_PIN_FUNCTION(aoss_cti),
	MSM_PIN_FUNCTION(atest_char0),
	MSM_PIN_FUNCTION(atest_char1),
	MSM_PIN_FUNCTION(atest_char2),
	MSM_PIN_FUNCTION(atest_char3),
	MSM_PIN_FUNCTION(atest_char_start),
	MSM_PIN_FUNCTION(atest_usb0),
	MSM_PIN_FUNCTION(atest_usb1),
	MSM_PIN_FUNCTION(atest_usb2),
	MSM_PIN_FUNCTION(atest_usb3),
	MSM_PIN_FUNCTION(audio_ref_clk),
	MSM_PIN_FUNCTION(bimc_dte0),
	MSM_PIN_FUNCTION(bimc_dte1),
	MSM_PIN_FUNCTION(char_exec_pending),
	MSM_PIN_FUNCTION(char_exec_release),
	MSM_PIN_FUNCTION(coex_uart),
	MSM_PIN_FUNCTION(dbg_out_clk),
	MSM_PIN_FUNCTION(ddr_bist_complete),
	MSM_PIN_FUNCTION(ddr_bist_fail),
	MSM_PIN_FUNCTION(ddr_bist_start),
	MSM_PIN_FUNCTION(ddr_bist_stop),
	MSM_PIN_FUNCTION(ddr_pxi0),
	MSM_PIN_FUNCTION(ddr_pxi1),
	MSM_PIN_FUNCTION(ebi2_a),
	MSM_PIN_FUNCTION(ebi2_lcd),
	MSM_PIN_FUNCTION(ebi2_lcd_te),
	MSM_PIN_FUNCTION(emac0_cdc0),
	MSM_PIN_FUNCTION(emac0_cdc1),
	MSM_PIN_FUNCTION(emac0_mcg),
	MSM_PIN_FUNCTION(emac0_ptp),
	MSM_PIN_FUNCTION(emac1_cdc0),
	MSM_PIN_FUNCTION(emac1_cdc1),
	MSM_PIN_FUNCTION(emac1_mcg),
	MSM_PIN_FUNCTION(emac1_ptp0),
	MSM_PIN_FUNCTION(emac1_ptp1),
	MSM_PIN_FUNCTION(emac1_ptp2),
	MSM_PIN_FUNCTION(emac1_ptp3),
	MSM_PIN_FUNCTION(emac2_cdc0),
	MSM_PIN_FUNCTION(emac2_cdc1),
	MSM_PIN_FUNCTION(emac2_mcg),
	MSM_PIN_FUNCTION(emac2_ptp0),
	MSM_PIN_FUNCTION(emac2_ptp1),
	MSM_PIN_FUNCTION(emac2_ptp2),
	MSM_PIN_FUNCTION(emac2_ptp3),
	MSM_PIN_FUNCTION(emac_pps_in),
	MSM_PIN_FUNCTION(espmi_coex_clk),
	MSM_PIN_FUNCTION(espmi_coex_data),
	MSM_PIN_FUNCTION(eth0_mdc),
	MSM_PIN_FUNCTION(eth0_mdio),
	MSM_PIN_FUNCTION(eth1_mdc),
	MSM_PIN_FUNCTION(eth1_mdio),
	MSM_PIN_FUNCTION(eth2_mdc),
	MSM_PIN_FUNCTION(eth2_mdio),
	MSM_PIN_FUNCTION(gcc_125_clk),
	MSM_PIN_FUNCTION(gcc_gp1_clk),
	MSM_PIN_FUNCTION(gcc_gp2_clk),
	MSM_PIN_FUNCTION(gcc_gp3_clk),
	MSM_PIN_FUNCTION(gcc_plltest_bypassnl),
	MSM_PIN_FUNCTION(gcc_plltest_resetn),
	MSM_PIN_FUNCTION(host_rst),
	MSM_PIN_FUNCTION(i2c0_s),
	MSM_PIN_FUNCTION(i2s0_data0),
	MSM_PIN_FUNCTION(i2s0_data1),
	MSM_PIN_FUNCTION(i2s0_sck),
	MSM_PIN_FUNCTION(i2s0_ws),
	MSM_PIN_FUNCTION(i2s1_data0),
	MSM_PIN_FUNCTION(i2s1_data1),
	MSM_PIN_FUNCTION(i2s1_sck),
	MSM_PIN_FUNCTION(i2s1_ws),
	MSM_PIN_FUNCTION(i2s2_data0),
	MSM_PIN_FUNCTION(i2s2_data1),
	MSM_PIN_FUNCTION(i2s2_sck),
	MSM_PIN_FUNCTION(i2s2_ws),
	MSM_PIN_FUNCTION(i2s_mclk),
	MSM_PIN_FUNCTION(i3c0_s_scl),
	MSM_PIN_FUNCTION(i3c0_s_sda),
	MSM_PIN_FUNCTION(ibi_i3c),
	MSM_PIN_FUNCTION(jitter_bist),
	MSM_PIN_FUNCTION(modem_pps),
	MSM_PIN_FUNCTION(native_tsense),
	MSM_PIN_FUNCTION(nav_dr_sync),
	MSM_PIN_FUNCTION(nav_gpio0),
	MSM_PIN_FUNCTION(nav_gpio1_mira),
	MSM_PIN_FUNCTION(nav_gpio1_mirb),
	MSM_PIN_FUNCTION(nav_gpio2_mira),
	MSM_PIN_FUNCTION(nav_gpio2_mirb),
	MSM_PIN_FUNCTION(nav_gpio2_mirc),
	MSM_PIN_FUNCTION(nav_gpio3),
	MSM_PIN_FUNCTION(nav_gpio4),
	MSM_PIN_FUNCTION(nav_gpio5),
	MSM_PIN_FUNCTION(nav_rffe),
	MSM_PIN_FUNCTION(pa_indicator),
	MSM_PIN_FUNCTION(pci_e),
	MSM_PIN_FUNCTION(pcie0_clkreq_n),
	MSM_PIN_FUNCTION(pcie0_perstn),
	MSM_PIN_FUNCTION(pcie1_clkreq_n),
	MSM_PIN_FUNCTION(pcie2_clkreq_n),
	MSM_PIN_FUNCTION(pcie3_clkreq_n),
	MSM_PIN_FUNCTION(pcie3_perstn),
	MSM_PIN_FUNCTION(pll_bist_sync),
	MSM_PIN_FUNCTION(pll_clk_aux),
	MSM_PIN_FUNCTION(pll_ref_clk),
	MSM_PIN_FUNCTION(prng_rosc0),
	MSM_PIN_FUNCTION(prng_rosc1),
	MSM_PIN_FUNCTION(prng_rosc2),
	MSM_PIN_FUNCTION(prng_rosc3),
	MSM_PIN_FUNCTION(qdss_cti),
	MSM_PIN_FUNCTION(qlink0_enable),
	MSM_PIN_FUNCTION(qlink0_request),
	MSM_PIN_FUNCTION(qlink0_wmss),
	MSM_PIN_FUNCTION(qup0_se0_l0),
	MSM_PIN_FUNCTION(qup0_se0_l1),
	MSM_PIN_FUNCTION(qup0_se0_l2),
	MSM_PIN_FUNCTION(qup0_se0_l3),
	MSM_PIN_FUNCTION(qup0_se1_l2),
	MSM_PIN_FUNCTION(qup0_se1_l3),
	MSM_PIN_FUNCTION(qup0_se2_l0),
	MSM_PIN_FUNCTION(qup0_se2_l1),
	MSM_PIN_FUNCTION(qup0_se2_l2),
	MSM_PIN_FUNCTION(qup0_se2_l3),
	MSM_PIN_FUNCTION(qup0_se3_l0),
	MSM_PIN_FUNCTION(qup0_se3_l1),
	MSM_PIN_FUNCTION(qup0_se3_l2),
	MSM_PIN_FUNCTION(qup0_se3_l3),
	MSM_PIN_FUNCTION(qup0_se4_l2_mira),
	MSM_PIN_FUNCTION(qup0_se4_l2_mirb),
	MSM_PIN_FUNCTION(qup0_se4_l3_mira),
	MSM_PIN_FUNCTION(qup0_se4_l3_mirb),
	MSM_PIN_FUNCTION(qup0_se5_l0),
	MSM_PIN_FUNCTION(qup0_se5_l1),
	MSM_PIN_FUNCTION(qup0_se6_l0_mira),
	MSM_PIN_FUNCTION(qup0_se6_l0_mirb),
	MSM_PIN_FUNCTION(qup0_se6_l1_mira),
	MSM_PIN_FUNCTION(qup0_se6_l1_mirb),
	MSM_PIN_FUNCTION(qup0_se6_l2_mira),
	MSM_PIN_FUNCTION(qup0_se6_l2_mirb),
	MSM_PIN_FUNCTION(qup0_se6_l3_mira),
	MSM_PIN_FUNCTION(qup0_se6_l3_mirb),
	MSM_PIN_FUNCTION(qup0_se7_l0),
	MSM_PIN_FUNCTION(qup0_se7_l1),
	MSM_PIN_FUNCTION(qup0_se7_l2),
	MSM_PIN_FUNCTION(qup0_se7_l3),
	MSM_PIN_FUNCTION(qup0_se8_l2_mira),
	MSM_PIN_FUNCTION(qup0_se8_l2_mirb),
	MSM_PIN_FUNCTION(qup0_se8_l3_mira),
	MSM_PIN_FUNCTION(qup0_se8_l3_mirb),
	MSM_PIN_FUNCTION(qup0_se9_l0_mira),
	MSM_PIN_FUNCTION(qup0_se9_l0_mirb),
	MSM_PIN_FUNCTION(qup0_se9_l1_mira),
	MSM_PIN_FUNCTION(qup0_se9_l1_mirb),
	MSM_PIN_FUNCTION(qup0_se9_l2_mira),
	MSM_PIN_FUNCTION(qup0_se9_l2_mirb),
	MSM_PIN_FUNCTION(qup0_se9_l3_mira),
	MSM_PIN_FUNCTION(qup0_se9_l3_mirb),
	MSM_PIN_FUNCTION(rgmii0_rx_ctl),
	MSM_PIN_FUNCTION(rgmii0_rxc),
	MSM_PIN_FUNCTION(rgmii0_rxd0),
	MSM_PIN_FUNCTION(rgmii0_rxd1),
	MSM_PIN_FUNCTION(rgmii0_rxd2),
	MSM_PIN_FUNCTION(rgmii0_rxd3),
	MSM_PIN_FUNCTION(rgmii0_tx_ctl),
	MSM_PIN_FUNCTION(rgmii0_txc),
	MSM_PIN_FUNCTION(rgmii0_txd0),
	MSM_PIN_FUNCTION(rgmii0_txd1),
	MSM_PIN_FUNCTION(rgmii0_txd2),
	MSM_PIN_FUNCTION(rgmii0_txd3),
	MSM_PIN_FUNCTION(sdc1_tb_trig),
	MSM_PIN_FUNCTION(sdc1_write_protect),
	MSM_PIN_FUNCTION(sgmii_phy_intr0_n),
	MSM_PIN_FUNCTION(sgmii_phy_intr1_n),
	MSM_PIN_FUNCTION(sgmii_phy_intr2_n),
	MSM_PIN_FUNCTION(spmi_coex_clk),
	MSM_PIN_FUNCTION(spmi_coex_data),
	MSM_PIN_FUNCTION(spmi_vgi),
	MSM_PIN_FUNCTION(tesic_gp_in0),
	MSM_PIN_FUNCTION(tesic_gp_in1),
	MSM_PIN_FUNCTION(tesic_gp_in2),
	MSM_PIN_FUNCTION(tesic_gp_in3),
	MSM_PIN_FUNCTION(tesic_gp_in4),
	MSM_PIN_FUNCTION(tesic_gp_in5),
	MSM_PIN_FUNCTION(tesic_gp_in6),
	MSM_PIN_FUNCTION(tesic_gp_out0),
	MSM_PIN_FUNCTION(tesic_gp_out1),
	MSM_PIN_FUNCTION(tesic_gp_out10),
	MSM_PIN_FUNCTION(tesic_gp_out2),
	MSM_PIN_FUNCTION(tesic_gp_out3),
	MSM_PIN_FUNCTION(tesic_gp_out4),
	MSM_PIN_FUNCTION(tesic_gp_out5),
	MSM_PIN_FUNCTION(tesic_gp_out6),
	MSM_PIN_FUNCTION(tesic_gp_out7),
	MSM_PIN_FUNCTION(tesic_gp_out8),
	MSM_PIN_FUNCTION(tesic_gp_out9),
	MSM_PIN_FUNCTION(tesic_jtag),
	MSM_PIN_FUNCTION(tesic_jtag_tck),
	MSM_PIN_FUNCTION(tesic_jtag_tdi),
	MSM_PIN_FUNCTION(tesic_jtag_tdo),
	MSM_PIN_FUNCTION(tesic_jtag_tms),
	MSM_PIN_FUNCTION(tmess_prng0),
	MSM_PIN_FUNCTION(tmess_prng1),
	MSM_PIN_FUNCTION(tmess_prng2),
	MSM_PIN_FUNCTION(tmess_prng3),
	MSM_PIN_FUNCTION(uim0_clk),
	MSM_PIN_FUNCTION(uim0_data),
	MSM_PIN_FUNCTION(uim0_present),
	MSM_PIN_FUNCTION(uim0_reset),
	MSM_PIN_FUNCTION(uim1_clk_mira),
	MSM_PIN_FUNCTION(uim1_clk_mirb),
	MSM_PIN_FUNCTION(uim1_data_mira),
	MSM_PIN_FUNCTION(uim1_data_mirb),
	MSM_PIN_FUNCTION(uim1_present_mira),
	MSM_PIN_FUNCTION(uim1_present_mirb),
	MSM_PIN_FUNCTION(uim1_reset_mira),
	MSM_PIN_FUNCTION(uim1_reset_mirb),
	MSM_PIN_FUNCTION(usb0_hs),
	MSM_PIN_FUNCTION(vfr_0),
	MSM_PIN_FUNCTION(vfr_1),
	MSM_PIN_FUNCTION(vsense_trigger_mirnat),
	MSM_PIN_FUNCTION(wcn_sw),
	MSM_PIN_FUNCTION(wcn_sw_ctrl),
};

static const msm_pin_function echo_pin_functions[] = {
	[0] = PINGROUP(0, uim1_data_mira, qup0_se9_l0_mira, _, _, native_tsense, _, _, _, _, _, _),
	[1] = PINGROUP(1, uim1_present_mira, qup0_se9_l3_mira, _, _, native_tsense, _, _, _, _, _, _),
	[2] = PINGROUP(2, uim1_reset_mira, qup0_se9_l1_mira, _, _, _, _, _, _, _, _, _),
	[3] = PINGROUP(3, uim1_clk_mira, qup0_se9_l2_mira, _, _, _, _, _, _, _, _, _),
	[4] = PINGROUP(4, uim0_data, aoss_cti, _, _, _, _, _, _, _, _, _),
	[5] = PINGROUP(5, uim0_present, sdc1_tb_trig, aoss_cti, _, _, _, _, _, _, _, _),
	[6] = PINGROUP(6, uim0_reset, aoss_cti, _, _, _, _, _, _, _, _, _),
	[7] = PINGROUP(7, uim0_clk, aoss_cti, _, _, _, _, _, _, _, _, _),
	[8] = PINGROUP(8, qup0_se0_l0, ddr_pxi0, _, native_tsense, _, _, _, _, _, _, _),
	[9] = PINGROUP(9, qup0_se0_l1, ddr_pxi0, _, native_tsense, _, _, _, _, _, _, _),
	[10] = PINGROUP(10, qup0_se0_l2, _, _, _, _, _, _, _, _, _, _),
	[11] = PINGROUP(11, qup0_se0_l3, _, _, _, _, _, _, _, _, _, _),
	[12] = PINGROUP(12, qup0_se1_l2, _, _, _, _, _, _, _, _, _, _),
	[13] = PINGROUP(13, qup0_se1_l3, _, _, _, _, _, _, _, _, _, _),
	[14] = PINGROUP(14, qup0_se2_l0, _, _, _, _, _, _, _, _, _, _),
	[15] = PINGROUP(15, qup0_se2_l1, char_exec_pending, tmess_prng3, _, _, _, _, _, _, _, _),
	[16] = PINGROUP(16, i2s0_ws, qup0_se2_l2, char_exec_release, _, _, _, _, _, _, _, _),
	[17] = PINGROUP(17, i2s0_data0, qup0_se2_l3, _, _, _, _, _, _, _, _, _),
	[18] = PINGROUP(18, i2s0_data1, _, _, _, _, _, _, _, _, _, _),
	[19] = PINGROUP(19, i2s0_sck, _, _, _, _, _, _, _, _, _, _),
	[20] = PINGROUP(20, i2s1_ws, _, _, _, _, _, _, _, _, _, _),
	[21] = PINGROUP(21, i2s1_data0, prng_rosc1, gcc_gp1_clk, ddr_pxi1, _, atest_usb2, _, _, _, _, _),
	[22] = PINGROUP(22, i2s1_data1, _, _, _, _, _, _, _, _, _, _),
	[23] = PINGROUP(23, i2s1_sck, _, _, _, _, _, _, _, _, _, _),
	[24] = PINGROUP(24, nav_gpio4, _, tmess_prng1, _, atest_char0, _, _, _, _, _, _),
	[25] = PINGROUP(25, gcc_125_clk, nav_gpio5, _, tmess_prng2, _, atest_char3, _, _, _, _, _),
	[26] = PINGROUP(26, _, _, _, _, _, _, _, _, _, _, _),
	[27] = PINGROUP(27, _, _, _, _, _, _, _, _, _, _, _),
	[28] = PINGROUP(28, _, _, _, _, _, _, _, _, _, _, _),
	[29] = PINGROUP(29, _, nav_rffe, _, bimc_dte0, _, _, _, _, _, _, _),
	[30] = PINGROUP(30, _, nav_rffe, _, _, _, _, _, _, _, _, _),
	[31] = PINGROUP(31, _, _, pll_clk_aux, gcc_plltest_bypassnl, ddr_pxi1, _, atest_usb3, _, _, _, _),
	[32] = PINGROUP(32, _, _, tmess_prng0, _, _, _, _, _, _, _, _),
	[33] = PINGROUP(33, _, nav_rffe, _, _, _, _, _, _, _, _, _),
	[34] = PINGROUP(34, _, nav_rffe, _, _, _, _, _, _, _, _, _),
	[35] = PINGROUP(35, nav_gpio1_mira, modem_pps, _, modem_pps, nav_gpio2_mira, emac0_ptp, emac0_ptp, gcc_plltest_resetn, _, _, _),
	[36] = PINGROUP(36, nav_gpio0, nav_dr_sync, nav_gpio3, _, _, _, _, _, _, _, _),
	[37] = PINGROUP(37, qlink0_enable, _, _, _, _, _, _, _, _, _, _),
	[38] = PINGROUP(38, qlink0_request, _, _, _, _, _, _, _, _, _, _),
	[39] = PINGROUP(39, qlink0_wmss, _, _, _, _, _, _, _, _, _, _),
	[40] = PINGROUP(40, wcn_sw_ctrl, _, bimc_dte1, _, _, _, _, _, _, _, _),
	[41] = PINGROUP(41, wcn_sw, _, _, bimc_dte1, _, _, _, _, _, _, _),
	[42] = PINGROUP(42, pci_e, _, _, atest_char2, _, _, _, _, _, _, _),
	[43] = PINGROUP(43, pcie0_clkreq_n, _, atest_char1, _, _, _, _, _, _, _, _),
	[44] = PINGROUP(44, pcie0_perstn, _, atest_char_start, _, _, _, _, _, _, _, _),
	[45] = PINGROUP(45, nav_gpio2_mirc, ddr_bist_complete, _, _, _, _, _, _, _, _, _),
	[46] = PINGROUP(46, qup0_se4_l2_mirb, coex_uart, ddr_bist_stop, _, _, _, _, _, _, _, _),
	[47] = PINGROUP(47, qup0_se4_l3_mirb, coex_uart, _, _, bimc_dte0, _, _, _, _, _, _),
	[48] = PINGROUP(48, espmi_coex_data, coex_uart, spmi_coex_data, ddr_bist_fail, _, _, _, _, _, _, _),
	[49] = PINGROUP(49, espmi_coex_clk, coex_uart, spmi_coex_clk, ddr_bist_start, _, _, _, _, _, _, _),
	[50] = PINGROUP(50, wcn_sw, spmi_vgi, _, _, _, _, _, _, _, _, _),
	[51] = PINGROUP(51, wcn_sw, spmi_vgi, _, _, _, _, _, _, _, _, _),
	[52] = PINGROUP(52, qup0_se3_l0, qdss_cti, qdss_cti, adsp_ext, _, _, _, _, _, _, _),
	[53] = PINGROUP(53, qup0_se3_l1, qdss_cti, qdss_cti, _, _, _, _, _, _, _, _),
	[54] = PINGROUP(54, qup0_se3_l2, _, _, _, _, _, _, _, _, _, _),
	[55] = PINGROUP(55, qup0_se3_l3, _, _, _, _, _, _, _, _, _, _),
	[56] = PINGROUP(56, _, _, _, _, _, _, _, _, _, _, _),
	[57] = PINGROUP(57, _, _, _, _, _, _, _, _, _, _, _),
	[58] = PINGROUP(58, _, pa_indicator, _, _, _, _, _, _, _, _, _),
	[59] = PINGROUP(59, _, _, _, _, _, _, _, _, _, _, _),
	[60] = PINGROUP(60, _, _, _, _, _, _, _, _, _, _, _),
	[61] = PINGROUP(61, _, _, _, _, _, _, _, _, _, _, _),
	[62] = PINGROUP(62, _, _, _, _, _, _, _, _, _, _, _),
	[63] = PINGROUP(63, _, _, _, _, _, _, _, _, _, _, _),
	[64] = PINGROUP(64, qup0_se4_l2_mira, _, _, _, _, _, _, _, _, _, _),
	[65] = PINGROUP(65, pcie3_clkreq_n, qup0_se4_l3_mira, _, _, _, _, _, _, _, _, _),
	[66] = PINGROUP(66, _, _, _, _, _, _, _, _, _, _, _),
	[67] = PINGROUP(67, _, _, _, _, _, _, _, _, _, _, _),
	[68] = PINGROUP(68, _, _, _, _, _, _, _, _, _, _, _),
	[69] = PINGROUP(69, _, _, _, _, _, _, _, _, _, _, _),
	[70] = PINGROUP(70, _, _, _, _, _, _, _, _, _, _, _),
	[71] = PINGROUP(71, _, _, _, _, _, _, _, _, _, _, _),
	[72] = PINGROUP(72, _, _, _, _, _, _, _, _, _, _, _),
	[73] = PINGROUP(73, _, _, _, _, _, _, _, _, _, _, _),
	[74] = PINGROUP(74, i2s_mclk, jitter_bist, _, _, _, _, _, _, _, _, _),
	[75] = PINGROUP(75, _, _, _, _, _, _, _, _, _, _, _),
	[76] = PINGROUP(76, _, _, _, _, _, _, _, _, _, _, _),
	[77] = PINGROUP(77, _, _, _, _, _, _, _, _, _, _, _),
	[78] = PINGROUP(78, qdss_cti, qdss_cti, _, _, _, _, _, _, _, _, _),
	[79] = PINGROUP(79, qdss_cti, qdss_cti, _, _, _, _, _, _, _, _, _),
	[80] = PINGROUP(80, usb0_hs, _, _, _, _, _, _, _, _, _, _),
	[81] = PINGROUP(81, _, _, _, _, _, _, _, _, _, _, _),
	[82] = PINGROUP(82, rgmii0_txc, tesic_gp_in0, _, _, _, _, _, _, _, _, _),
	[83] = PINGROUP(83, rgmii0_txd0, tesic_gp_in1, emac0_ptp, emac0_ptp, emac0_mcg, _, _, _, _, _, _),
	[84] = PINGROUP(84, rgmii0_txd1, tesic_gp_in2, emac0_ptp, emac0_mcg, _, _, _, _, _, _, _),
	[85] = PINGROUP(85, rgmii0_txd2, tesic_gp_in3, emac0_ptp, emac0_mcg, _, _, _, _, _, _, _),
	[86] = PINGROUP(86, rgmii0_txd3, tesic_gp_in4, eth2_mdc, _, _, _, _, _, _, _, _),
	[87] = PINGROUP(87, rgmii0_tx_ctl, tesic_gp_in5, eth2_mdio, _, _, _, _, _, _, _, _),
	[88] = PINGROUP(88, rgmii0_rxc, tesic_gp_in6, _, _, _, _, _, _, _, _, _),
	[89] = PINGROUP(89, rgmii0_rxd0, tesic_gp_out0, sgmii_phy_intr2_n, emac0_ptp, emac0_ptp, emac0_mcg, _, _, _, _, _),
	[90] = PINGROUP(90, rgmii0_rxd1, tesic_gp_out1, emac1_mcg, _, _, _, _, _, _, _, _),
	[91] = PINGROUP(91, rgmii0_rxd2, tesic_gp_out2, _, _, _, _, _, _, _, _, _),
	[92] = PINGROUP(92, rgmii0_rxd3, tesic_gp_out3, emac1_mcg, _, _, _, _, _, _, _, _),
	[93] = PINGROUP(93, rgmii0_rx_ctl, tesic_gp_out4, emac1_mcg, _, _, _, _, _, _, _, _),
	[94] = PINGROUP(94, eth0_mdc, emac2_mcg, prng_rosc2, gcc_gp2_clk, vsense_trigger_mirnat, emac1_cdc1, atest_usb0, _, _, _, _),
	[95] = PINGROUP(95, eth0_mdio, tesic_gp_out5, _, _, _, _, _, _, _, _, _),
	[96] = PINGROUP(96, tesic_gp_out6, emac2_mcg, _, _, _, _, _, _, _, _, _),
	[97] = PINGROUP(97, sgmii_phy_intr0_n, tesic_gp_out7, emac2_mcg, _, _, _, _, _, _, _, _),
	[98] = PINGROUP(98, ebi2_lcd_te, tesic_gp_out9, qup0_se9_l3_mirb, _, _, _, _, _, _, _, _),
	[99] = PINGROUP(99, ebi2_lcd, tesic_gp_out10, qup0_se9_l0_mirb, _, _, _, _, _, _, _, _),
	[100] = PINGROUP(100, ebi2_a, tesic_gp_out8, qup0_se9_l1_mirb, _, _, _, _, _, _, _, _),
	[101] = PINGROUP(101, ebi2_lcd, qup0_se9_l2_mirb, _, _, _, _, _, _, _, _, _),
	[102] = PINGROUP(102, _, _, _, _, _, _, _, _, _, _, _),
	[103] = PINGROUP(103, audio_ref_clk, _, _, _, _, _, _, _, _, _, _),
	[104] = PINGROUP(104, nav_gpio2_mirb, modem_pps, modem_pps, nav_gpio1_mirb, _, _, _, _, _, _, _),
	[105] = PINGROUP(105, pcie3_perstn, _, _, _, _, _, _, _, _, _, _),
	[106] = PINGROUP(106, eth1_mdc, _, atest_usb1, _, _, _, _, _, _, _, _),
	[107] = PINGROUP(107, eth1_mdio, pll_ref_clk, prng_rosc3, gcc_gp3_clk, emac1_cdc0, dbg_out_clk, _, _, _, _, _),
	[108] = PINGROUP(108, _, _, _, _, _, _, _, _, _, _, _),
	[109] = PINGROUP(109, sgmii_phy_intr1_n, _, _, _, _, _, _, _, _, _, _),
	[110] = PINGROUP(110, qup0_se5_l0, ibi_i3c, i2c0_s, sdc1_write_protect, _, _, _, _, _, _, _),
	[111] = PINGROUP(111, qup0_se5_l1, ibi_i3c, i2c0_s, _, _, _, _, _, _, _, _),
	[112] = PINGROUP(112, qup0_se6_l0_mira, ibi_i3c, i2c0_s, i3c0_s_sda, uim1_data_mirb, emac1_ptp0, _, _, _, _, _),
	[113] = PINGROUP(113, qup0_se6_l1_mira, ibi_i3c, i2c0_s, i3c0_s_scl, uim1_present_mirb, emac1_ptp1, _, _, _, _, _),
	[114] = PINGROUP(114, qup0_se6_l2_mira, tesic_jtag_tdi, uim1_reset_mirb, emac1_ptp2, pll_bist_sync, prng_rosc0, emac0_cdc1, _, _, _, _),
	[115] = PINGROUP(115, qup0_se6_l3_mira, tesic_jtag_tdo, uim1_clk_mirb, emac1_ptp3, emac0_cdc0, _, _, _, _, _, _),
	[116] = PINGROUP(116, qup0_se7_l0, tesic_jtag_tms, emac2_ptp0, emac2_ptp0, emac2_cdc1, _, _, _, _, _, _),
	[117] = PINGROUP(117, qup0_se7_l1, tesic_jtag_tck, emac2_ptp1, emac2_ptp1, emac2_cdc0, _, _, _, _, _, _),
	[118] = PINGROUP(118, qup0_se7_l2, qup0_se8_l2_mirb, emac2_ptp2, emac2_ptp2, _, _, _, _, _, _, _),
	[119] = PINGROUP(119, qup0_se7_l3, tesic_jtag, emac0_ptp, _, _, _, _, _, _, _, _),
	[120] = PINGROUP(120, _, _, _, _, _, _, _, _, _, _, _),
	[121] = PINGROUP(121, pcie2_clkreq_n, _, _, _, _, _, _, _, _, _, _),
	[122] = PINGROUP(122, emac1_mcg, _, _, _, _, _, _, _, _, _, _),
	[123] = PINGROUP(123, emac0_ptp, emac0_ptp, emac0_ptp, emac0_ptp, emac1_ptp0, emac1_ptp1, emac1_ptp2, emac1_ptp3, _, _, _),
	[124] = PINGROUP(124, pcie1_clkreq_n, qup0_se8_l2_mira, emac2_mcg, _, _, _, _, _, _, _, _),
	[125] = PINGROUP(125, qup0_se8_l3_mira, _, _, _, _, _, _, _, _, _, _),
	[126] = PINGROUP(126, host_rst, _, _, _, _, _, _, _, _, _, _),
	[127] = PINGROUP(127, i2s2_ws, emac_pps_in, _, _, _, _, _, _, _, _, _),
	[128] = PINGROUP(128, i2s2_data0, qup0_se6_l2_mirb, _, _, _, _, _, _, _, _, _),
	[129] = PINGROUP(129, i2s2_data1, qup0_se6_l3_mirb, vfr_0, _, _, _, _, _, _, _, _),
	[130] = PINGROUP(130, i2s2_sck, qup0_se6_l0_mirb, ibi_i3c, vfr_1, _, _, _, _, _, _, _),
	[131] = PINGROUP(131, qup0_se6_l1_mirb, ibi_i3c, _, _, _, _, _, _, _, _, _),
	[132] = PINGROUP(132, qup0_se8_l3_mirb, emac1_mcg, emac2_ptp3, emac2_ptp3, _, _, _, _, _, _, _),
};

static const struct msm_special_pin_data echo_special_pins_data[] = {
	[0] = SDC_QDSD_PINGROUP("sdc1_rclk", 0x18a000, 2, 0),
	[1] = SDC_QDSD_PINGROUP("sdc1_clk", 0x18a000, 0, 6),
	[2] = SDC_QDSD_PINGROUP("sdc1_cmd", 0x18a004, 11, 3),
	[3] = SDC_QDSD_PINGROUP("sdc1_data", 0x18a004, 9, 0),
};

static const char *echo_get_function_name(struct udevice *dev,
					   unsigned int selector)
{
	return msm_pinctrl_functions[selector].name;
}

static const char *echo_get_pin_name(struct udevice *dev,
				      unsigned int selector)
{
	if (selector >= 133 && selector <= 136)
		snprintf(pin_name, MAX_PIN_NAME_LEN, "%s",
			 echo_special_pins_data[selector - 133].name);
	else
		snprintf(pin_name, MAX_PIN_NAME_LEN, "gpio%u", selector);

	return pin_name;
}

static int echo_get_function_mux(__maybe_unused unsigned int pin,
				  unsigned int selector)
{
	unsigned int i;
	const msm_pin_function *func = echo_pin_functions + pin;

	for (i = 0; i < MSM_PIN_FUNCTION_COUNT; i++)
		if ((*func)[i] == selector)
			return i;

	pr_err("Can't find requested function for pin %u\n", pin);

	return -EINVAL;
}

static const struct msm_pinctrl_data echo_data = {
	.pin_data = {
		.pin_count = 137,
		.special_pins_start = 133,
		.special_pins_data = echo_special_pins_data,
	},
	.functions_count = ARRAY_SIZE(msm_pinctrl_functions),
	.get_function_name = echo_get_function_name,
	.get_function_mux = echo_get_function_mux,
	.get_pin_name = echo_get_pin_name,
};

static const struct udevice_id msm_pinctrl_ids[] = {
	{
		.compatible = "qcom,echo-pinctrl",
		.data = (ulong)&echo_data
	},
	{ /* Sentinel */ }
};

U_BOOT_DRIVER(pinctrl_echo) = {
	.name		= "pinctrl_echo",
	.id		= UCLASS_NOP,
	.of_match	= msm_pinctrl_ids,
	.ops		= &msm_pinctrl_ops,
	.bind		= msm_pinctrl_bind,
	.flags		= DM_FLAG_PRE_RELOC,
};
