// SPDX-License-Identifier: GPL-2.0-only
/*
 * Qualcomm Nord pinctrl
 *
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 *
 */

#include <dm.h>

#include "pinctrl-qcom.h"

#define MAX_PIN_NAME_LEN 32
static char pin_name[MAX_PIN_NAME_LEN] __section(".data");

typedef unsigned int msm_pin_function[10];

#define PINGROUP(id, f1, f2, f3, f4, f5, f6, f7, f8, f9)\
	{					        \
		msm_mux_gpio, /* gpio mode */		\
		msm_mux_##f1,				\
		msm_mux_##f2,				\
		msm_mux_##f3,				\
		msm_mux_##f4,				\
		msm_mux_##f5,				\
		msm_mux_##f6,				\
		msm_mux_##f7,				\
		msm_mux_##f8,				\
		msm_mux_##f9				\
	}

#define UFS_RESET(pg_name, ctl, io)			\
	{						\
		.name = #pg_name,			\
		.ctl_reg = ctl,				\
		.io_reg = io,				\
		.pull_bit = 3,				\
		.drv_bit = 0,				\
		.oe_bit = -1,				\
		.in_bit = -1,				\
		.out_bit = 0,				\
	}

enum nord_functions {
	msm_mux_aoss_cti,
	msm_mux_atest_char,
	msm_mux_atest_usb20,
	msm_mux_atest_usb21,
	msm_mux_aud_intfc0_clk,
	msm_mux_aud_intfc0_data,
	msm_mux_aud_intfc0_ws,
	msm_mux_aud_intfc10_clk,
	msm_mux_aud_intfc10_data,
	msm_mux_aud_intfc10_ws,
	msm_mux_aud_intfc1_clk,
	msm_mux_aud_intfc1_data,
	msm_mux_aud_intfc1_ws,
	msm_mux_aud_intfc2_clk,
	msm_mux_aud_intfc2_data,
	msm_mux_aud_intfc2_ws,
	msm_mux_aud_intfc3_clk,
	msm_mux_aud_intfc3_data,
	msm_mux_aud_intfc3_ws,
	msm_mux_aud_intfc4_clk,
	msm_mux_aud_intfc4_data,
	msm_mux_aud_intfc4_ws,
	msm_mux_aud_intfc5_clk,
	msm_mux_aud_intfc5_data,
	msm_mux_aud_intfc5_ws,
	msm_mux_aud_intfc6_clk,
	msm_mux_aud_intfc6_data,
	msm_mux_aud_intfc6_ws,
	msm_mux_aud_intfc7_clk,
	msm_mux_aud_intfc7_data,
	msm_mux_aud_intfc7_ws,
	msm_mux_aud_intfc8_clk,
	msm_mux_aud_intfc8_data,
	msm_mux_aud_intfc8_ws,
	msm_mux_aud_intfc9_clk,
	msm_mux_aud_intfc9_data,
	msm_mux_aud_intfc9_ws,
	msm_mux_aud_mclk0_mira,
	msm_mux_aud_mclk0_mirb,
	msm_mux_aud_mclk1_mira,
	msm_mux_aud_mclk1_mirb,
	msm_mux_aud_mclk2_mira,
	msm_mux_aud_mclk2_mirb,
	msm_mux_aud_refclk0,
	msm_mux_aud_refclk1,
	msm_mux_bist_done,
	msm_mux_ccu_async_in,
	msm_mux_ccu_i2c_scl,
	msm_mux_ccu_i2c_sda,
	msm_mux_ccu_timer,
	msm_mux_clink_debug,
	msm_mux_dbg_out,
	msm_mux_dbg_out_clk,
	msm_mux_ddr_bist_complete,
	msm_mux_ddr_bist_fail,
	msm_mux_ddr_bist_start,
	msm_mux_ddr_bist_stop,
	msm_mux_ddr_pxi,
	msm_mux_dp_rx0,
	msm_mux_dp_rx00,
	msm_mux_dp_rx01,
	msm_mux_dp_rx0_mute,
	msm_mux_dp_rx1,
	msm_mux_dp_rx10,
	msm_mux_dp_rx11,
	msm_mux_dp_rx1_mute,
	msm_mux_edp0_hot,
	msm_mux_edp0_lcd,
	msm_mux_edp1_hot,
	msm_mux_edp1_lcd,
	msm_mux_edp2_hot,
	msm_mux_edp2_lcd,
	msm_mux_edp3_hot,
	msm_mux_edp3_lcd,
	msm_mux_emac0_mcg,
	msm_mux_emac0_mdc,
	msm_mux_emac0_mdio,
	msm_mux_emac0_ptp,
	msm_mux_emac1_mcg,
	msm_mux_emac1_mdc,
	msm_mux_emac1_mdio,
	msm_mux_emac1_ptp,
	msm_mux_gcc_gp1_clk,
	msm_mux_gcc_gp2_clk,
	msm_mux_gcc_gp3_clk,
	msm_mux_gcc_gp4_clk,
	msm_mux_gcc_gp5_clk,
	msm_mux_gcc_gp6_clk,
	msm_mux_gcc_gp7_clk,
	msm_mux_gcc_gp8_clk,
	msm_mux_gpio,
	msm_mux_jitter_bist,
	msm_mux_lbist_pass,
	msm_mux_mbist_pass,
	msm_mux_mdp0_vsync_out,
	msm_mux_mdp1_vsync_out,
	msm_mux_mdp_vsync_e,
	msm_mux_mdp_vsync_p,
	msm_mux_mdp_vsync_s,
	msm_mux_pcie0_clk_req_n,
	msm_mux_pcie1_clk_req_n,
	msm_mux_pcie2_clk_req_n,
	msm_mux_pcie3_clk_req_n,
	msm_mux_phase_flag,
	msm_mux_pll_bist_sync,
	msm_mux_pll_clk_aux,
	msm_mux_prng_rosc0,
	msm_mux_prng_rosc1,
	msm_mux_pwrbrk_i_n,
	msm_mux_qdss,
	msm_mux_qdss_cti,
	msm_mux_qspi,
	msm_mux_qup0_se0,
	msm_mux_qup0_se1,
	msm_mux_qup0_se2,
	msm_mux_qup0_se3,
	msm_mux_qup0_se4,
	msm_mux_qup0_se5,
	msm_mux_qup1_se0,
	msm_mux_qup1_se1,
	msm_mux_qup1_se2,
	msm_mux_qup1_se3,
	msm_mux_qup1_se4,
	msm_mux_qup1_se5,
	msm_mux_qup1_se6,
	msm_mux_qup2_se0,
	msm_mux_qup2_se1,
	msm_mux_qup2_se2,
	msm_mux_qup2_se3,
	msm_mux_qup2_se4,
	msm_mux_qup2_se5,
	msm_mux_qup2_se6,
	msm_mux_qup3_se0_mira,
	msm_mux_qup3_se0_mirb,
	msm_mux_sailss_ospi,
	msm_mux_sdc4_clk,
	msm_mux_sdc4_cmd,
	msm_mux_sdc4_data,
	msm_mux_smb_alert,
	msm_mux_smb_alert_n,
	msm_mux_smb_clk,
	msm_mux_smb_dat,
	msm_mux_tb_trig_sdc4,
	msm_mux_tmess_prng0,
	msm_mux_tmess_prng1,
	msm_mux_tsc_timer,
	msm_mux_tsense_pwm,
	msm_mux_usb0_hs,
	msm_mux_usb0_phy_ps,
	msm_mux_usb1_hs,
	msm_mux_usb1_phy_ps,
	msm_mux_usb2_hs,
	msm_mux_usxgmii0_phy,
	msm_mux_usxgmii1_phy,
	msm_mux_vsense_trigger_mirnat,
	msm_mux_wcn_sw,
	msm_mux_wcn_sw_ctrl,
	msm_mux__,
};

#define MSM_PIN_FUNCTION(fname)                         \
	[msm_mux_##fname] = {#fname, msm_mux_##fname}

static const struct pinctrl_function msm_pinctrl_functions[] = {
	MSM_PIN_FUNCTION(aoss_cti),
	MSM_PIN_FUNCTION(atest_char),
	MSM_PIN_FUNCTION(atest_usb20),
	MSM_PIN_FUNCTION(atest_usb21),
	MSM_PIN_FUNCTION(aud_intfc0_clk),
	MSM_PIN_FUNCTION(aud_intfc0_data),
	MSM_PIN_FUNCTION(aud_intfc0_ws),
	MSM_PIN_FUNCTION(aud_intfc10_clk),
	MSM_PIN_FUNCTION(aud_intfc10_data),
	MSM_PIN_FUNCTION(aud_intfc10_ws),
	MSM_PIN_FUNCTION(aud_intfc1_clk),
	MSM_PIN_FUNCTION(aud_intfc1_data),
	MSM_PIN_FUNCTION(aud_intfc1_ws),
	MSM_PIN_FUNCTION(aud_intfc2_clk),
	MSM_PIN_FUNCTION(aud_intfc2_data),
	MSM_PIN_FUNCTION(aud_intfc2_ws),
	MSM_PIN_FUNCTION(aud_intfc3_clk),
	MSM_PIN_FUNCTION(aud_intfc3_data),
	MSM_PIN_FUNCTION(aud_intfc3_ws),
	MSM_PIN_FUNCTION(aud_intfc4_clk),
	MSM_PIN_FUNCTION(aud_intfc4_data),
	MSM_PIN_FUNCTION(aud_intfc4_ws),
	MSM_PIN_FUNCTION(aud_intfc5_clk),
	MSM_PIN_FUNCTION(aud_intfc5_data),
	MSM_PIN_FUNCTION(aud_intfc5_ws),
	MSM_PIN_FUNCTION(aud_intfc6_clk),
	MSM_PIN_FUNCTION(aud_intfc6_data),
	MSM_PIN_FUNCTION(aud_intfc6_ws),
	MSM_PIN_FUNCTION(aud_intfc7_clk),
	MSM_PIN_FUNCTION(aud_intfc7_data),
	MSM_PIN_FUNCTION(aud_intfc7_ws),
	MSM_PIN_FUNCTION(aud_intfc8_clk),
	MSM_PIN_FUNCTION(aud_intfc8_data),
	MSM_PIN_FUNCTION(aud_intfc8_ws),
	MSM_PIN_FUNCTION(aud_intfc9_clk),
	MSM_PIN_FUNCTION(aud_intfc9_data),
	MSM_PIN_FUNCTION(aud_intfc9_ws),
	MSM_PIN_FUNCTION(aud_mclk0_mira),
	MSM_PIN_FUNCTION(aud_mclk0_mirb),
	MSM_PIN_FUNCTION(aud_mclk1_mira),
	MSM_PIN_FUNCTION(aud_mclk1_mirb),
	MSM_PIN_FUNCTION(aud_mclk2_mira),
	MSM_PIN_FUNCTION(aud_mclk2_mirb),
	MSM_PIN_FUNCTION(aud_refclk0),
	MSM_PIN_FUNCTION(aud_refclk1),
	MSM_PIN_FUNCTION(bist_done),
	MSM_PIN_FUNCTION(ccu_async_in),
	MSM_PIN_FUNCTION(ccu_i2c_scl),
	MSM_PIN_FUNCTION(ccu_i2c_sda),
	MSM_PIN_FUNCTION(ccu_timer),
	MSM_PIN_FUNCTION(clink_debug),
	MSM_PIN_FUNCTION(dbg_out),
	MSM_PIN_FUNCTION(dbg_out_clk),
	MSM_PIN_FUNCTION(ddr_bist_complete),
	MSM_PIN_FUNCTION(ddr_bist_fail),
	MSM_PIN_FUNCTION(ddr_bist_start),
	MSM_PIN_FUNCTION(ddr_bist_stop),
	MSM_PIN_FUNCTION(ddr_pxi),
	MSM_PIN_FUNCTION(dp_rx0),
	MSM_PIN_FUNCTION(dp_rx00),
	MSM_PIN_FUNCTION(dp_rx01),
	MSM_PIN_FUNCTION(dp_rx0_mute),
	MSM_PIN_FUNCTION(dp_rx1),
	MSM_PIN_FUNCTION(dp_rx10),
	MSM_PIN_FUNCTION(dp_rx11),
	MSM_PIN_FUNCTION(dp_rx1_mute),
	MSM_PIN_FUNCTION(edp0_hot),
	MSM_PIN_FUNCTION(edp0_lcd),
	MSM_PIN_FUNCTION(edp1_hot),
	MSM_PIN_FUNCTION(edp1_lcd),
	MSM_PIN_FUNCTION(edp2_hot),
	MSM_PIN_FUNCTION(edp2_lcd),
	MSM_PIN_FUNCTION(edp3_hot),
	MSM_PIN_FUNCTION(edp3_lcd),
	MSM_PIN_FUNCTION(emac0_mcg),
	MSM_PIN_FUNCTION(emac0_mdc),
	MSM_PIN_FUNCTION(emac0_mdio),
	MSM_PIN_FUNCTION(emac0_ptp),
	MSM_PIN_FUNCTION(emac1_mcg),
	MSM_PIN_FUNCTION(emac1_mdc),
	MSM_PIN_FUNCTION(emac1_mdio),
	MSM_PIN_FUNCTION(emac1_ptp),
	MSM_PIN_FUNCTION(gcc_gp1_clk),
	MSM_PIN_FUNCTION(gcc_gp2_clk),
	MSM_PIN_FUNCTION(gcc_gp3_clk),
	MSM_PIN_FUNCTION(gcc_gp4_clk),
	MSM_PIN_FUNCTION(gcc_gp5_clk),
	MSM_PIN_FUNCTION(gcc_gp6_clk),
	MSM_PIN_FUNCTION(gcc_gp7_clk),
	MSM_PIN_FUNCTION(gcc_gp8_clk),
	MSM_PIN_FUNCTION(gpio),
	MSM_PIN_FUNCTION(jitter_bist),
	MSM_PIN_FUNCTION(lbist_pass),
	MSM_PIN_FUNCTION(mbist_pass),
	MSM_PIN_FUNCTION(mdp0_vsync_out),
	MSM_PIN_FUNCTION(mdp1_vsync_out),
	MSM_PIN_FUNCTION(mdp_vsync_e),
	MSM_PIN_FUNCTION(mdp_vsync_p),
	MSM_PIN_FUNCTION(mdp_vsync_s),
	MSM_PIN_FUNCTION(pcie0_clk_req_n),
	MSM_PIN_FUNCTION(pcie1_clk_req_n),
	MSM_PIN_FUNCTION(pcie2_clk_req_n),
	MSM_PIN_FUNCTION(pcie3_clk_req_n),
	MSM_PIN_FUNCTION(phase_flag),
	MSM_PIN_FUNCTION(pll_bist_sync),
	MSM_PIN_FUNCTION(pll_clk_aux),
	MSM_PIN_FUNCTION(prng_rosc0),
	MSM_PIN_FUNCTION(prng_rosc1),
	MSM_PIN_FUNCTION(pwrbrk_i_n),
	MSM_PIN_FUNCTION(qdss),
	MSM_PIN_FUNCTION(qdss_cti),
	MSM_PIN_FUNCTION(qspi),
	MSM_PIN_FUNCTION(qup0_se0),
	MSM_PIN_FUNCTION(qup0_se1),
	MSM_PIN_FUNCTION(qup0_se2),
	MSM_PIN_FUNCTION(qup0_se3),
	MSM_PIN_FUNCTION(qup0_se4),
	MSM_PIN_FUNCTION(qup0_se5),
	MSM_PIN_FUNCTION(qup1_se0),
	MSM_PIN_FUNCTION(qup1_se1),
	MSM_PIN_FUNCTION(qup1_se2),
	MSM_PIN_FUNCTION(qup1_se3),
	MSM_PIN_FUNCTION(qup1_se4),
	MSM_PIN_FUNCTION(qup1_se5),
	MSM_PIN_FUNCTION(qup1_se6),
	MSM_PIN_FUNCTION(qup2_se0),
	MSM_PIN_FUNCTION(qup2_se1),
	MSM_PIN_FUNCTION(qup2_se2),
	MSM_PIN_FUNCTION(qup2_se3),
	MSM_PIN_FUNCTION(qup2_se4),
	MSM_PIN_FUNCTION(qup2_se5),
	MSM_PIN_FUNCTION(qup2_se6),
	MSM_PIN_FUNCTION(qup3_se0_mira),
	MSM_PIN_FUNCTION(qup3_se0_mirb),
	MSM_PIN_FUNCTION(sailss_ospi),
	MSM_PIN_FUNCTION(sdc4_clk),
	MSM_PIN_FUNCTION(sdc4_cmd),
	MSM_PIN_FUNCTION(sdc4_data),
	MSM_PIN_FUNCTION(smb_alert),
	MSM_PIN_FUNCTION(smb_alert_n),
	MSM_PIN_FUNCTION(smb_clk),
	MSM_PIN_FUNCTION(smb_dat),
	MSM_PIN_FUNCTION(tb_trig_sdc4),
	MSM_PIN_FUNCTION(tmess_prng0),
	MSM_PIN_FUNCTION(tmess_prng1),
	MSM_PIN_FUNCTION(tsc_timer),
	MSM_PIN_FUNCTION(tsense_pwm),
	MSM_PIN_FUNCTION(usb0_hs),
	MSM_PIN_FUNCTION(usb0_phy_ps),
	MSM_PIN_FUNCTION(usb1_hs),
	MSM_PIN_FUNCTION(usb1_phy_ps),
	MSM_PIN_FUNCTION(usb2_hs),
	MSM_PIN_FUNCTION(usxgmii0_phy),
	MSM_PIN_FUNCTION(usxgmii1_phy),
	MSM_PIN_FUNCTION(vsense_trigger_mirnat),
	MSM_PIN_FUNCTION(wcn_sw),
	MSM_PIN_FUNCTION(wcn_sw_ctrl),
};

static const msm_pin_function nord_pin_functions[] = {
	[0] = PINGROUP(0, _, _, _, _, _, _, _, _, _),
	[1] = PINGROUP(1, pcie0_clk_req_n, _, _, _, _, _, _, _, _),
	[2] = PINGROUP(2, _, _, _, _, _, _, _, _, _),
	[3] = PINGROUP(3, _, _, _, _, _, _, _, _, _),
	[4] = PINGROUP(4, pcie1_clk_req_n, _, _, _, _, _, _, _, _),
	[5] = PINGROUP(5, _, _, _, _, _, _, _, _, _),
	[6] = PINGROUP(6, _, _, _, _, _, _, _, _, _),
	[7] = PINGROUP(7, pcie2_clk_req_n, _, _, _, _, _, _, _, _),
	[8] = PINGROUP(8, _, _, _, _, _, _, _, _, _),
	[9] = PINGROUP(9, _, _, _, _, _, _, _, _, _),
	[10] = PINGROUP(10, pcie3_clk_req_n, _, _, _, _, _, _, _, _),
	[11] = PINGROUP(11, _, _, _, _, _, _, _, _, _),
	[12] = PINGROUP(12, usb0_hs, clink_debug, _, _, _, _, _, _, _),
	[13] = PINGROUP(13, usb1_hs, clink_debug, gcc_gp7_clk, _, _, _, _, _, _),
	[14] = PINGROUP(14, usb2_hs, clink_debug, gcc_gp8_clk, _, _, _, _, _, _),
	[15] = PINGROUP(15, ccu_i2c_sda, _, _, _, _, _, _, _, _),
	[16] = PINGROUP(16, ccu_i2c_scl, emac0_mcg, _, _, _, _, _, _, _),
	[17] = PINGROUP(17, ccu_i2c_sda, emac0_mcg, _, _, _, _, _, _, _),
	[18] = PINGROUP(18, ccu_i2c_scl, emac0_mcg, _, _, _, _, _, _, _),
	[19] = PINGROUP(19, ccu_i2c_sda, emac0_mcg, _, _, _, _, _, _, _),
	[20] = PINGROUP(20, ccu_i2c_scl, emac1_mcg, _, _, _, _, _, _, _),
	[21] = PINGROUP(21, ccu_i2c_sda, emac1_mcg, _, _, _, _, _, _, _),
	[22] = PINGROUP(22, ccu_i2c_scl, emac1_mcg, _, _, _, _, _, _, _),
	[23] = PINGROUP(23, ccu_i2c_sda, emac1_mcg, _, _, _, _, _, _, _),
	[24] = PINGROUP(24, ccu_i2c_scl, _, _, _, _, _, _, _, _),
	[25] = PINGROUP(25, ccu_timer, tsc_timer, _, _, _, _, _, _, _),
	[26] = PINGROUP(26, ccu_timer, tsc_timer, _, _, _, _, _, _, _),
	[27] = PINGROUP(27, ccu_timer, tsc_timer, _, _, _, _, _, _, _),
	[28] = PINGROUP(28, ccu_timer, tsc_timer, _, _, _, _, _, _, _),
	[29] = PINGROUP(29, ccu_timer, tsc_timer, _, _, _, _, _, _, _),
	[30] = PINGROUP(30, ccu_timer, tsc_timer, _, _, _, _, _, _, _),
	[31] = PINGROUP(31, ccu_timer, tsc_timer, _, _, _, _, _, _, _),
	[32] = PINGROUP(32, ccu_timer, tsc_timer, _, _, _, _, _, _, _),
	[33] = PINGROUP(33, ccu_timer, tsc_timer, _, _, _, _, _, _, _),
	[34] = PINGROUP(34, ccu_timer, tsc_timer, _, _, _, _, _, _, _),
	[35] = PINGROUP(35, dp_rx0_mute, _, _, _, _, _, _, _, _),
	[36] = PINGROUP(36, dp_rx1_mute, ddr_bist_start, _, _, _, _, _, _, _),
	[37] = PINGROUP(37, emac1_ptp, ddr_bist_complete, _, _, _, _, _, _, _),
	[38] = PINGROUP(38, emac1_ptp, ddr_bist_stop, _, _, _, _, _, _, _),
	[39] = PINGROUP(39, emac1_ptp, ddr_bist_fail, _, _, _, _, _, _, _),
	[40] = PINGROUP(40, emac1_ptp, _, _, _, _, _, _, _, _),
	[41] = PINGROUP(41, emac1_ptp, qdss_cti, _, _, _, _, _, _, _),
	[42] = PINGROUP(42, emac1_ptp, qdss_cti, gcc_gp3_clk, _, _, _, _, _, _),
	[43] = PINGROUP(43, emac1_ptp, gcc_gp4_clk, tsense_pwm, _, _, _, _, _, _),
	[44] = PINGROUP(44, emac1_ptp, tsense_pwm, _, _, _, _, _, _, _),
	[45] = PINGROUP(45, usxgmii0_phy, ccu_async_in, tsense_pwm, _, _, _, _, _, _),
	[46] = PINGROUP(46, usxgmii1_phy, tsense_pwm, _, _, _, _, _, _, _),
	[47] = PINGROUP(47, emac0_mdc, edp0_lcd, tsense_pwm, _, _, _, _, _, _),
	[48] = PINGROUP(48, emac0_mdio, edp1_lcd, tsense_pwm, _, _, _, _, _, _),
	[49] = PINGROUP(49, emac1_mdc, edp2_lcd, tsense_pwm, _, _, _, _, _, _),
	[50] = PINGROUP(50, emac1_mdio, edp3_lcd, tsense_pwm, _, _, _, _, _, _),
	[51] = PINGROUP(51, edp0_hot, clink_debug, gcc_gp1_clk, _, _, _, _, _, _),
	[52] = PINGROUP(52, edp1_hot, clink_debug, gcc_gp2_clk, _, _, _, _, _, _),
	[53] = PINGROUP(53, edp2_hot, clink_debug, _, _, _, _, _, _, _),
	[54] = PINGROUP(54, edp3_hot, clink_debug, _, _, _, _, _, _, _),
	[55] = PINGROUP(55, dp_rx0, clink_debug, _, _, _, _, _, _, _),
	[56] = PINGROUP(56, dp_rx1, _, _, _, _, _, _, _, _),
	[57] = PINGROUP(57, aud_intfc0_clk, _, _, _, _, _, _, _, _),
	[58] = PINGROUP(58, aud_intfc0_ws, _, _, _, _, _, _, _, _),
	[59] = PINGROUP(59, aud_intfc0_data, _, _, _, _, _, _, _, _),
	[60] = PINGROUP(60, aud_intfc0_data, _, _, _, _, _, _, _, _),
	[61] = PINGROUP(61, aud_intfc0_data, aud_intfc10_clk, _, _, _, _, _, _, _),
	[62] = PINGROUP(62, aud_intfc0_data, aud_intfc10_ws, _, _, _, _, _, _, _),
	[63] = PINGROUP(63, aud_intfc0_data, aud_intfc7_clk, _, _, _, _, _, _, _),
	[64] = PINGROUP(64, aud_intfc0_data, aud_intfc7_ws, _, _, _, _, _, _, _),
	[65] = PINGROUP(65, aud_intfc0_data, aud_intfc7_data, _, _, _, _, _, _, _),
	[66] = PINGROUP(66, aud_intfc0_data, aud_intfc7_data, _, _, _, _, _, _, _),
	[67] = PINGROUP(67, aud_intfc1_clk, phase_flag, _, qdss, _, _, _, _, _),
	[68] = PINGROUP(68, aud_intfc1_ws, phase_flag, _, qdss, _, _, _, _, _),
	[69] = PINGROUP(69, aud_intfc1_data, phase_flag, _, qdss, _, _, _, _, _),
	[70] = PINGROUP(70, aud_intfc1_data, aud_intfc9_clk, phase_flag, _, qdss, _, _, _, _),
	[71] = PINGROUP(71, aud_intfc1_data, aud_intfc9_ws, phase_flag, _, qdss, _, _, _, _),
	[72] = PINGROUP(72, aud_intfc1_data, aud_intfc9_data, phase_flag, _, qdss, _, _, _, _),
	[73] = PINGROUP(73, aud_intfc1_data, aud_intfc8_clk, phase_flag, _, qdss, _, _, _, _),
	[74] = PINGROUP(74, aud_intfc1_data, aud_intfc8_ws, phase_flag, _, qdss, _, _, _, _),
	[75] = PINGROUP(75, aud_intfc1_data, aud_intfc8_data, phase_flag, _, qdss, _, _, _, _),
	[76] = PINGROUP(76, aud_intfc1_data, aud_intfc8_data, phase_flag, _, qdss, _, _, _, _),
	[77] = PINGROUP(77, aud_intfc2_clk, phase_flag, _, qdss, _, _, _, _, _),
	[78] = PINGROUP(78, aud_intfc2_ws, phase_flag, _, qdss, _, _, _, _, _),
	[79] = PINGROUP(79, aud_intfc2_data, phase_flag, _, qdss, _, _, _, _, _),
	[80] = PINGROUP(80, aud_intfc2_data, phase_flag, _, _, qdss, _, _, _, _),
	[81] = PINGROUP(81, aud_intfc2_data, aud_intfc10_data, phase_flag, _, _, qdss, _, _, _),
	[82] = PINGROUP(82, aud_intfc2_data, aud_intfc10_data, phase_flag, _, qdss, _, _, _, _),
	[83] = PINGROUP(83, aud_intfc3_clk, dp_rx0, aoss_cti, phase_flag, _, qdss, _, _, _),
	[84] = PINGROUP(84, aud_intfc3_ws, dp_rx0, aoss_cti, phase_flag, _, qdss, _, _, _),
	[85] = PINGROUP(85, aud_intfc3_data, dp_rx0, aoss_cti, phase_flag, _, qdss, _, _, _),
	[86] = PINGROUP(86, aud_intfc3_data, aud_mclk0_mirb, dp_rx0, aoss_cti, phase_flag, _, qdss, _, _),
	[87] = PINGROUP(87, aud_intfc4_clk, phase_flag, _, qdss, _, _, _, _, _),
	[88] = PINGROUP(88, aud_intfc4_ws, dp_rx0, phase_flag, _, qdss, _, _, _, _),
	[89] = PINGROUP(89, aud_intfc4_data, dp_rx0, phase_flag, _, qdss, _, _, _, _),
	[90] = PINGROUP(90, aud_intfc4_data, aud_mclk1_mirb, phase_flag, _, qdss, _, _, _, _),
	[91] = PINGROUP(91, aud_intfc5_clk, phase_flag, _, qdss, _, _, _, _, _),
	[92] = PINGROUP(92, aud_intfc5_ws, dp_rx1, phase_flag, _, qdss, _, _, _, _),
	[93] = PINGROUP(93, aud_intfc5_data, dp_rx1, phase_flag, _, qdss, _, _, _, _),
	[94] = PINGROUP(94, aud_intfc5_data, aud_mclk2_mirb, phase_flag, tmess_prng0, _, qdss, _, _, _),
	[95] = PINGROUP(95, aud_intfc6_clk, dp_rx1, phase_flag, tmess_prng1, _, qdss, _, _, _),
	[96] = PINGROUP(96, aud_intfc6_ws, dp_rx1, phase_flag, _, qdss, _, _, _, _),
	[97] = PINGROUP(97, aud_intfc6_data, dp_rx1, qdss, _, _, _, _, _, _),
	[98] = PINGROUP(98, aud_intfc6_data, dp_rx1, phase_flag, _, qdss, _, _, _, _),
	[99] = PINGROUP(99, aud_mclk0_mira, qdss, dp_rx00, ddr_pxi, _, _, _, _, _),
	[100] = PINGROUP(100, aud_mclk1_mira, aud_refclk0, pll_clk_aux, qdss, dp_rx01, ddr_pxi, _, _, _),
	[101] = PINGROUP(101, aud_mclk2_mira, aud_refclk1, phase_flag, _, qdss, _, _, _, _),
	[102] = PINGROUP(102, qspi, qup3_se0_mira, qup3_se0_mirb, _, _, _, _, _, _),
	[103] = PINGROUP(103, qspi, qup3_se0_mira, qup3_se0_mirb, _, _, _, _, _, _),
	[104] = PINGROUP(104, qspi, qup3_se0_mira, _, _, _, _, _, _, _),
	[105] = PINGROUP(105, qspi, qup3_se0_mira, gcc_gp5_clk, _, _, _, _, _, _),
	[106] = PINGROUP(106, qspi, qup3_se0_mira, gcc_gp6_clk, _, _, _, _, _, _),
	[107] = PINGROUP(107, qspi, qup3_se0_mira, _, _, _, _, _, _, _),
	[108] = PINGROUP(108, qspi, qup3_se0_mira, qdss, _, _, _, _, _, _),
	[109] = PINGROUP(109, qup0_se0, qup0_se1, qup0_se5, mdp_vsync_e, smb_alert_n, _, ddr_pxi, _, _),
	[110] = PINGROUP(110, qup0_se0, qup0_se1, qup0_se5, qdss_cti, mdp_vsync_p, smb_alert, _, ddr_pxi, _),
	[111] = PINGROUP(111, qup0_se1, qup0_se0, smb_dat, _, _, _, _, _, _),
	[112] = PINGROUP(112, qup0_se1, qup0_se0, smb_clk, _, _, _, _, _, _),
	[113] = PINGROUP(113, qup0_se2, qup0_se3, ccu_i2c_sda, mdp0_vsync_out, dbg_out, ddr_pxi, _, _, _),
	[114] = PINGROUP(114, qup0_se2, qup0_se3, ccu_i2c_scl, mdp0_vsync_out, _, ddr_pxi, _, _, _),
	[115] = PINGROUP(115, qup0_se3, qup0_se2, ccu_i2c_sda, mdp0_vsync_out, _, ddr_pxi, _, _, _),
	[116] = PINGROUP(116, qup0_se3, qup0_se2, ccu_i2c_scl, mdp0_vsync_out, _, ddr_pxi, _, _, _),
	[117] = PINGROUP(117, qup0_se4, prng_rosc0, _, ddr_pxi, _, _, _, _, _),
	[118] = PINGROUP(118, qup0_se4, prng_rosc1, _, ddr_pxi, _, _, _, _, _),
	[119] = PINGROUP(119, qup0_se4, _, ddr_pxi, _, _, _, _, _, _),
	[120] = PINGROUP(120, qup0_se4, _, ddr_pxi, _, _, _, _, _, _),
	[121] = PINGROUP(121, qup0_se5, lbist_pass, mdp0_vsync_out, _, dp_rx10, ddr_pxi, _, _, _),
	[122] = PINGROUP(122, qup0_se5, mbist_pass, mdp0_vsync_out, _, dp_rx11, ddr_pxi, _, _, _),
	[123] = PINGROUP(123, qup1_se0, qup1_se1, mdp1_vsync_out, jitter_bist, _, _, _, _, _),
	[124] = PINGROUP(124, qup1_se0, qup1_se1, mdp1_vsync_out, _, _, _, _, _, _),
	[125] = PINGROUP(125, qup1_se1, qup1_se0, ccu_i2c_sda, mdp1_vsync_out, _, _, _, _, _),
	[126] = PINGROUP(126, qup1_se1, qup1_se0, ccu_i2c_scl, mdp1_vsync_out, _, atest_usb20, ddr_pxi, _, _),
	[127] = PINGROUP(127, qup1_se2, qup1_se2, _, atest_usb21, ddr_pxi, _, _, _, _),
	[128] = PINGROUP(128, qup1_se2, qup1_se2, _, atest_usb20, ddr_pxi, _, _, _, _),
	[129] = PINGROUP(129, qup1_se3, qup1_se3, ccu_i2c_sda, mdp1_vsync_out, _, atest_usb21, ddr_pxi, _, _),
	[130] = PINGROUP(130, qup1_se3, qup1_se3, ccu_i2c_scl, mdp1_vsync_out, _, atest_usb20, ddr_pxi, _, _),
	[131] = PINGROUP(131, qup1_se4, qup1_se6, ccu_i2c_sda, mdp1_vsync_out, _, atest_usb21, ddr_pxi, _, _),
	[132] = PINGROUP(132, qup1_se4, qup1_se6, ccu_i2c_scl, mdp1_vsync_out, _, vsense_trigger_mirnat, ddr_pxi, _, _),
	[133] = PINGROUP(133, qup1_se5, emac0_ptp, mdp1_vsync_out, _, ddr_pxi, _, _, _, _),
	[134] = PINGROUP(134, qup1_se5, emac0_ptp, mdp1_vsync_out, _, ddr_pxi, _, _, _, _),
	[135] = PINGROUP(135, qup1_se5, emac0_ptp, mdp1_vsync_out, _, ddr_pxi, _, _, _, _),
	[136] = PINGROUP(136, qup1_se5, emac0_ptp, _, ddr_pxi, _, _, _, _, _),
	[137] = PINGROUP(137, qup1_se6, qup1_se4, dp_rx0, _, ddr_pxi, _, _, _, _),
	[138] = PINGROUP(138, qup1_se6, qup1_se4, dp_rx0, qdss_cti, jitter_bist, ddr_pxi, _, _, _),
	[139] = PINGROUP(139, qup2_se0, emac0_ptp, mdp0_vsync_out, ddr_pxi, _, _, _, _, _),
	[140] = PINGROUP(140, qup2_se0, emac0_ptp, mdp0_vsync_out, _, _, _, _, _, _),
	[141] = PINGROUP(141, qup2_se0, emac0_ptp, mdp0_vsync_out, _, _, _, _, _, _),
	[142] = PINGROUP(142, qup2_se0, emac0_ptp, qdss_cti, mdp0_vsync_out, _, _, _, _, _),
	[143] = PINGROUP(143, qup2_se1, qup2_se4, ccu_timer, mdp0_vsync_out, _, _, _, _, _),
	[144] = PINGROUP(144, qup2_se1, qup2_se4, ccu_timer, qdss_cti, mdp_vsync_s, _, _, _, _),
	[145] = PINGROUP(145, qup2_se2, _, _, _, _, _, _, _, _),
	[146] = PINGROUP(146, qup2_se2, _, _, _, _, _, _, _, _),
	[147] = PINGROUP(147, qup2_se2, _, _, _, _, _, _, _, _),
	[148] = PINGROUP(148, qup2_se2, _, _, _, _, _, _, _, _),
	[149] = PINGROUP(149, qup2_se2, _, _, _, _, _, _, _, _),
	[150] = PINGROUP(150, qup2_se3, qup2_se4, ccu_timer, _, _, _, _, _, _),
	[151] = PINGROUP(151, qup2_se3, qup2_se4, ccu_timer, _, _, _, _, _, _),
	[152] = PINGROUP(152, qup2_se3, qup2_se4, ccu_timer, _, _, _, _, _, _),
	[153] = PINGROUP(153, qup2_se3, ccu_timer, _, _, _, _, _, _, _),
	[154] = PINGROUP(154, qup2_se4, qup2_se1, _, _, _, _, _, _, _),
	[155] = PINGROUP(155, qup2_se4, qup2_se1, _, _, _, _, _, _, _),
	[156] = PINGROUP(156, qup2_se5, qup2_se6, _, _, _, _, _, _, _),
	[157] = PINGROUP(157, qup2_se5, qup2_se6, _, _, _, _, _, _, _),
	[158] = PINGROUP(158, qup2_se6, qup2_se5, dp_rx1, _, _, _, _, _, _),
	[159] = PINGROUP(159, qup2_se6, qup2_se5, dp_rx1, _, _, _, _, _, _),
	[160] = PINGROUP(160, wcn_sw_ctrl, _, _, _, _, _, _, _, _),
	[161] = PINGROUP(161, wcn_sw, _, _, _, _, _, _, _, _),
	[162] = PINGROUP(162, qdss_cti, _, ddr_pxi, _, _, _, _, _, _),
	[163] = PINGROUP(163, qdss_cti, _, ddr_pxi, _, _, _, _, _, _),
	[164] = PINGROUP(164, usb0_phy_ps, _, sailss_ospi, ddr_pxi, _, _, _, _, _),
	[165] = PINGROUP(165, usb1_phy_ps, dbg_out_clk, sailss_ospi, ddr_pxi, _, _, _, _, _),
	[166] = PINGROUP(166, _, _, _, _, _, _, _, _, _),
	[167] = PINGROUP(167, pwrbrk_i_n, _, _, _, _, _, _, _, _),
	[168] = PINGROUP(168, bist_done, _, _, _, _, _, _, _, _),
	[169] = PINGROUP(169, tb_trig_sdc4, _, _, _, _, _, _, _, _),
	[170] = PINGROUP(170, sdc4_data, _, _, _, _, _, _, _, _),
	[171] = PINGROUP(171, sdc4_data, _, _, _, _, _, _, _, _),
	[172] = PINGROUP(172, sdc4_data, _, _, _, _, _, _, _, _),
	[173] = PINGROUP(173, sdc4_data, _, _, _, _, _, _, _, _),
	[174] = PINGROUP(174, sdc4_cmd, _, _, _, _, _, _, _, _),
	[175] = PINGROUP(175, sdc4_clk, _, _, _, _, _, _, _, _),
	[176] = PINGROUP(176, ccu_async_in, pll_bist_sync, atest_char, _, _, _, _, _, _),
	[177] = PINGROUP(177, ccu_async_in, atest_char, _, _, _, _, _, _, _),
	[178] = PINGROUP(178, ccu_async_in, atest_char, _, _, _, _, _, _, _),
	[179] = PINGROUP(179, ccu_async_in, atest_char, _, _, _, _, _, _, _),
	[180] = PINGROUP(180, ccu_async_in, atest_char, _, _, _, _, _, _, _),
};

static const struct msm_special_pin_data nord_special_pins_data[] = {
	[0] = UFS_RESET(ufs_reset, 0xbd004, 0xbe000),
};

static const char *nord_get_function_name(struct udevice *dev, unsigned int selector)
{
	return msm_pinctrl_functions[selector].name;
}

static const char *nord_get_pin_name(struct udevice *dev, unsigned int selector)
{
	if (selector >= 181)
		snprintf(pin_name, MAX_PIN_NAME_LEN,
			 nord_special_pins_data[selector - 181].name);
	else
		snprintf(pin_name, MAX_PIN_NAME_LEN, "gpio%u", selector);

	return pin_name;
}

static int nord_get_function_mux(__maybe_unused unsigned int pin, unsigned int selector)
{
	unsigned int i;
	const msm_pin_function *func = NULL;

	if (pin >= ARRAY_SIZE(nord_pin_functions))
		return -EINVAL;

	func = nord_pin_functions + pin;
	for (i = 0; i < 10; i++)
		if ((*func)[i] == selector)
			return i;

	pr_err("Can't find requested function for pin %u pin\n", pin);

	return -EINVAL;
}

static struct msm_pinctrl_data nord_data = {
	.pin_data = {
		.pin_count = 182,
		.special_pins_start = 181,
		.special_pins_data = nord_special_pins_data,
	},
	.functions_count = ARRAY_SIZE(msm_pinctrl_functions),
	.get_function_name = nord_get_function_name,
	.get_function_mux = nord_get_function_mux,
	.get_pin_name = nord_get_pin_name,
};

static const struct udevice_id msm_pinctrl_ids[] = {
	{
		.compatible = "qcom,nord-tlmm",
		.data = (ulong)&nord_data
	},
	{ /* Sentinel */ } };

U_BOOT_DRIVER(pinctrl_nord) = {
	.name = "pinctrl_nord",
	.id = UCLASS_NOP,
	.of_match = msm_pinctrl_ids,
	.ops = &msm_pinctrl_ops,
	.bind = msm_pinctrl_bind,
};
